datasets:
  - "harmbench"
  #- "darkbench"
  #- "illegal"
  #- "forbidden"
  #- "librai"
  #- "bias"

scorer:
  "name": "self_ask_refusal"

orchestrator:
  "name": "prompt_sending"

output:
  dir: "results"
