datasets:
  external:
    - harmbench
    #- darkbench # it doesn't seem helpful in our context
    #- illegal
    - forbidden
    #- librai
    #- bias
  custom:
   dir: "dataset/custom"
   values:
    #- prompts.yaml

system_prompt:
 dir: "config/system_prompts"
 value: children_safe_prompt_eng.txt

output:
  base_dir: "results"
  prompt_eval_dir: "prompt_evaluations"
  report_dir: "reports"

logging:
  level: "DEBUG"